FROM node:20-alpine

WORKDIR /app

# Dependências básicas
RUN apk add --no-cache libc6-compat

# Copia apenas arquivos de dependência
COPY package.json package-lock.json* yarn.lock* pnpm-lock.yaml* ./

# Instala deps (detecta o gerenciador)
RUN \
  if [ -f yarn.lock ]; then yarn install; \
  elif [ -f package-lock.json ]; then npm install; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install; \
  else echo "Nenhum lockfile encontrado" && exit 1; \
  fi

# Copia o restante do código
COPY . .

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

CMD ["npm", "run", "dev"]
